<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = array(
            array('title' => 'ASPIRE 3','slug' => 'aspire-3','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 1,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),
            array('title' => 'EXTENSA','slug' => 'extensa','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 1,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),
            array('title' => 'HELIOUS','slug' => 'helious','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 1,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),
            array('title' => 'NITRO 5','slug' => 'nitro-5','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 1,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),
            array('title' => 'SWIFT GO','slug' => 'swift-go','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 1,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),
            array('title' => 'TRAVELMATE','slug' => 'travelmate','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 1,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),
            array('title' => 'ZEPHYRUS','slug' => 'zephyrus','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 2,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),
            array('title' => 'ZEPHYRUS DUO','slug' => 'zephyrus-duo','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 2,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),
            array('title' => 'TUF','slug' => 'tuf','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 2,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),
            array('title' => 'VIVOBOOK','slug' => 'vivobook','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 2,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),
            array('title' => 'CHROMEBOOK','slug' => 'chromebook','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 3,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),
            array('title' => 'ENVY','slug' => 'envy','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 3,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),
            array('title' => 'VICTUS','slug' => 'victus','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 3,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),
            array('title' => 'INSPIRON','slug' => 'inspiron','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 4,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),
            array('title' => 'LATITUDE','slug' => 'latitude','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 4,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),
            array('title' => 'XPS','slug' => 'xps','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 4,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),
            array('title' => 'MACBOOK','slug' => 'macbook','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','shipping_returns' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.','price' => 500, 'compare_price' => 100,'category_id' => 1,'sub_categories_id' => 1,'brand_id' => 5,'is_featured' => 'Yes','sku' => random_int(1000,9999),'barcode' => random_int(100000,999999),'track_qty' => 'Yes','qty' => random_int(5,15),'status' => 1),

        );
        DB::table('products')->insert($products);
    }
}
